//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Admin_Login", ReplyAction="*")]
        Web3.ServiceReference1.Admin_LoginResponse Admin_Login(Web3.ServiceReference1.Admin_LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Admin_LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Admin_Login", Namespace="http://tempuri.org/", Order=0)]
        public Web3.ServiceReference1.Admin_LoginRequestBody Body;
        
        public Admin_LoginRequest() {
        }
        
        public Admin_LoginRequest(Web3.ServiceReference1.Admin_LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Admin_LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public Admin_LoginRequestBody() {
        }
        
        public Admin_LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Admin_LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Admin_LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web3.ServiceReference1.Admin_LoginResponseBody Body;
        
        public Admin_LoginResponse() {
        }
        
        public Admin_LoginResponse(Web3.ServiceReference1.Admin_LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Admin_LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Admin_LoginResult;
        
        public Admin_LoginResponseBody() {
        }
        
        public Admin_LoginResponseBody(int Admin_LoginResult) {
            this.Admin_LoginResult = Admin_LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Web3.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Web3.ServiceReference1.WebService1Soap>, Web3.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web3.ServiceReference1.Admin_LoginResponse Web3.ServiceReference1.WebService1Soap.Admin_Login(Web3.ServiceReference1.Admin_LoginRequest request) {
            return base.Channel.Admin_Login(request);
        }
        
        public int Admin_Login(string username, string password) {
            Web3.ServiceReference1.Admin_LoginRequest inValue = new Web3.ServiceReference1.Admin_LoginRequest();
            inValue.Body = new Web3.ServiceReference1.Admin_LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Web3.ServiceReference1.Admin_LoginResponse retVal = ((Web3.ServiceReference1.WebService1Soap)(this)).Admin_Login(inValue);
            return retVal.Body.Admin_LoginResult;
        }
    }
}
